# Dockerfile para el frontend
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar servidor frontend y archivos estáticos
COPY server-frontend.js .
COPY frontend ./frontend

# Exponer puerto
EXPOSE 8081

# Comando para ejecutar el servidor
CMD ["node", "server-frontend.js"]
