# Configuración principal del Sistema de Salud Digital

# Configuración básica de la aplicación Spring Boot
spring:
  application:
    name: sistema-salud-digital
  profiles:
    active: postgresql

# Configuración del servidor web
server:
  port: 8080
  servlet:
    context-path: /api

# Configuración de registros y logs del sistema
logging:
  level:
    com.clinica.salud: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/salud-digital.log

# Configuración de endpoints de monitoreo y salud
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuración específica para perfil PostgreSQL
---
spring:
  config:
    activate:
      on-profile: postgresql
  
  # Configuración de conexión a base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_salud
    username: postgres
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Configuración de JPA y Hibernate para manejo de entidades
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false  # Desactiva la conexión perezosa en la vista
  
  # Configuración de serialización JSON con Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  # Configuración de inicialización de scripts SQL
  sql:
    init:
      mode: never  # Desactivado porque se gestionará manualmente