# ===================================================================
# SISTEMA DE SALUD DIGITAL - CONFIGURACIÓN PRINCIPAL
# ===================================================================

# ------------------
# Configuración básica de la aplicación
# ------------------
spring:
  application:
    name: sistema-salud-digital
  profiles:
    active: postgresql

# ------------------
# Configuración del servidor
# ------------------
server:
  port: 8080
  servlet:
    context-path: /api

# ------------------
# Configuración de registros (logs)
# ------------------
logging:
  level:
    com.clinica.salud: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/salud-digital.log

# ------------------
# Configuración de monitoreo y gestión
# ------------------
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# ===================================================================
# CONFIGURACIÓN ESPECÍFICA DE PERFIL: POSTGRESQL
# ===================================================================
---
spring:
  config:
    activate:
      on-profile: postgresql
  
  # ------------------
  # Configuración de base de datos PostgreSQL
  # ------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_salud
    username: postgres
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # ------------------
  # Configuración de JPA/Hibernate
  # ------------------  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false  # Desactiva la conexión perezosa en la vista
  
  # ------------------
  # Configuración de Jackson (JSON)
  # ------------------
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  # ------------------
  # Configuración de inicialización SQL
  # ------------------
  sql:
    init:
      mode: never  # Desactivado porque se gestionará manualmente